name: flutter_theme_designer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  flex_color_picker: ^3.7.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  flutter_web_plugins:
    sdk: flutter
  go_router: ^16.2.0
  riverpod_annotation: ^3.0.0-dev.17
  string_scanner: ^1.4.1

dev_dependencies:
  build_runner: ^2.7.0
  custom_lint: ^0.8.0

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

flutter:
  uses-material-design: true
