name: flutter_theme_designer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  device_preview:
    path: ./packages/device_preview
  flex_color_picker: ^3.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.1.2
  riverpod_annotation: ^2.3.5
  string_scanner: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.6.4

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
